title: Ahmad Adel Muhammad (ASquaredM)
description: Student at Cairo University Faculty of Engineering
author:
  name: Ahmad Adel Muhammad
  nickname: ASquaredM
hostname: ASquaredM.github.io # used to determine if google analytics should be triggered
url: https://ASquaredM.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title/

# stuff for jekyll-seo-tag
social:
  name: Ahmad Adel Muhammad
  links:
    - https://github.com/ASquaredM
    - https://www.linkedin.com/in/ahmad-a-muhammad
    - https://www.facebook.com/profile.php?id=1389086705



# main page content
email:
  title: pbagnpg\100wvzru\056zr
  href: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#080;&#114;&#111;&#078;&#111;&#111;&#098;&#087;&#097;&#114;&#110;&#105;&#110;&#103;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"

links:

  - name: github
    url: https://github.com/ASquaredM
    class: fa-github
  - name: linkedin
    url: https://www.linkedin.com/in/ahmad-a-muhammad
    class: fa-linkedin
  - name: facebook
    url: https://www.facebook.com/profile.php?id=1389086705
    class: fa-facebook
#  - name: cv (pdf)
#    id: resume
#    type: download
#    url: http://assets.jimeh.me/jim-myhrberg-cv.pdf
#    class: fa-file-text-o

# additional stuff
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
